import type { LintConfigContribution } from '../types'

export function createJsConfig(): LintConfigContribution {
  return {
    plugins: ['eslint', 'oxc', 'unicorn', 'import'],
    categories: { correctness: 'off' },
    env: {
      browser: true,
      node: true,
      es2024: true
    },
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'no-async-promise-executor': 'error',
      'no-caller': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTaggedTemplates: true,
          allowTernary: true,
        },
      ],
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': [
        'error',
        {
          args: 'none',
          caughtErrors: 'none',
          ignoreRestSiblings: true,
          vars: 'all',
        },
      ],
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-useless-rename': 'error',
      'no-with': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      curly: 'error',
      yoda: 'error',
      'default-param-last': 'error',
      'prefer-const': 'error',
      'prefer-rest-params': 'error',
      'require-await': 'error',
      'symbol-description': 'error',

      'oxc/bad-array-method-on-arguments': 'error',
      'oxc/bad-char-at-comparison': 'error',
      'oxc/bad-comparison-sequence': 'error',
      'oxc/bad-min-max-func': 'error',
      'oxc/bad-object-literal-comparison': 'error',
      'oxc/bad-replace-all-arg': 'error',
      'oxc/const-comparisons': 'error',
      'oxc/double-comparisons': 'error',
      'oxc/erasing-op': 'error',
      'oxc/missing-throw': 'error',
      'oxc/number-arg-out-of-range': 'error',
      'oxc/only-used-in-recursion': 'error',
      'oxc/uninvoked-array-callback': 'error',

      'unicorn/no-await-in-promise-methods': 'error',
      'unicorn/no-empty-file': 'error',
      'unicorn/no-invalid-fetch-options': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-new-array': 'error',
      'unicorn/no-single-promise-in-promise-methods': 'error',
      'unicorn/no-unnecessary-await': 'error',
      'unicorn/no-useless-fallback-in-spread': 'error',
      'unicorn/no-useless-length-check': 'error',
      'unicorn/no-useless-spread': 'error',
      'unicorn/prefer-set-size': 'error',
      'unicorn/prefer-string-starts-ends-with': 'error',

      'import/default': 'error',
      'import/namespace': 'error',
      'import/first': 'error',
      'import/no-duplicates': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-self-import': 'error',
    },
  }
}
